### ISSUE TITLE
replace links to old wiki.trezor.io by new help center links https://trezor.io/learn

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite-guide#3]
Article name | Category | Type | Current URL | Change to | Checked
-- | -- | -- | -- | -- | --
Passphrase | Security | Guide to KB | https://blog.trezor.io/is-your-passphrase-strong-enough-d687f44c63af | https://trezor.io/learn/a/passphrases-and-hidden-wallets | No
Shamir Backup | Security | Guide to KB | https://wiki.trezor.io/Shamir_Backup | https://trezor.io/learn/a/what-is-shamir-backup | No
Single Backup | Security | Guide to Shop | https://wiki.trezor.io/Recovery_seed | https://trezor.io/learn/a/how-to-use-a-recovery-seed | No
Single Backup | Security | Guide to KB | https://wiki.trezor.io/Recovery_seed | https://trezor.io/learn/a/how-to-use-a-recovery-seed | No
Supported Coins | Supported Crypto | Guide to Trezor Web | https://trezor.io/coins/ | https://trezor.io/coins/ | No
Supported Coins | Supported Crypto | Guide to Shop | https://shop.trezor.io/btc-only/ | https://trezor.io/learn/a/bitcoin-only-firmware-on-trezor | No
Accounts | Suite Basics | Guide to KB | https://wiki.trezor.io/Taproot | https://trezor.io/learn/a/what-is-taproot | No
Accounts | Suite Basics | Guide to KB | https://wiki.trezor.io/User_manual:Updating_the_Trezor_device_firmware | https://trezor.io/learn/a/update-trezor-device-firmware | No
Suite Guide | Suite Basics | Guide to Trezor Web | https://trezor.io/coins/ | https://trezor.io/coins/ | No
Suite Guide | Suite Basics | Guide to KB | https://wiki.trezor.io/ | https://trezor.io/support/ | No
Locktime | Suite Basics | Guide to KB | https://wiki.trezor.io/Transaction | https://trezor.io/learn/a/addresses-transaction-history | No
Locktime | Suite Basics | Guide to KB | https://wiki.trezor.io/Trezor | https://trezor.io/learn/a/locktime-in-trezor-suite-app | No
Send Overview | Suite Basics | Guide to KB | https://wiki.trezor.io/Taproot | https://trezor.io/learn/a/what-is-taproot | No
Contact Support | Support & Feedback | Guide to KB | https://trezor.io/support/ | https://trezor.io/support/ | No

[Suite Guide links bce97844542e4f6a9c0c7dd5c918044b (2).csv](https://github.com/trezor/trezor-suite-guide/files/9852663/Suite.Guide.links.bce97844542e4f6a9c0c7dd5c918044b.2.csv)

**Comment by b-irving** [comment]
@matejkriz all have been updated in Gitbook.
