### ISSUE TITLE
Fix images in Suite Guide

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite-guide#4]
Images from gitbook are in markdown in this form for some reason:
`<figure><img src="{relative path}" alt=""><figcaption></figcaption></figure>`
(not sure if it's because some update or the way we use gitbook)

It used to be:
`![]({relative path})`

Suite understand only the the other format.

**Comment by matejkriz** [comment]
see commit https://github.com/trezor/trezor-suite-guide/commit/177c50cfc833bcfad487f0cceeb5e64bbf5b9b87 and bc342d45cbe36514105e02db27c040c7b3b4d5e6 🙉

**Comment by komret** [comment]
According to [GitBook docs](https://docs.gitbook.com/content-creation/blocks/insert-images), the problematic syntax is used when `alt` text is provided. But `alt` is just an empty string in the commits referenced above...

**Comment by bosomt** [comment]
**QA OK**

checked web version of Suite guide and pictures are rendered as expected

**Info:**
 - Suite version: web 23.6.0 (58b905adc1eb8dbdb4074654b5a669cd4670b3b8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Comment by komret** [comment]
Reopening until https://github.com/trezor/trezor-suite/pull/8504 is merged.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 23.6.0 (d720d04cbbe56ff0913f459401f22d30ff06640d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
